### ISSUE TITLE
Don't use this plugin with nvim-tree.lua

### ISSUE THREAD

**Issue by nyngwang** [sunjon/Shade.nvim#23] opened 2021-10-27 09:01 UTC
It will cause a lot of error like the following:

```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:347: Vim:E444: Cannot close last window
```

Which will cost you so much time and find nothing.

**Comment by petrosAth** [comment] 2021-10-30 09:58
> 
> 
> It will cause a lot of error like the following:
> 
> ```
> E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:347: Vim:E444: Cannot close last window
> ```
> 
> Which will cost you so much time and find nothing.

After five hours of bug hunting I came here to say this!

**Comment by sunjon** [comment] 2021-12-01 19:26
The issue is https://github.com/neovim/neovim/issues/11440 and affects any plugin that has a single window with a float. I was aware of the problem when I wrote the plugin, but couldn't come up with a viable workaround at the time. There's a couple of Neovim PR's that aim to solve it.

**Comment by sunjon** [comment] 2022-02-07 02:35
Closing issue and will reference the underlying problem in the readme.

**Closed by sunjon** 2022-02-07 02:35 UTC
